// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ufGt-8hN-8C4VY39r4gIEWq8qScuht0',
    appId: '1:866164282450:web:18e91e7b1c89d85c8cfb8b',
    messagingSenderId: '866164282450',
    projectId: 'tradget-7498e',
    authDomain: 'tradget-7498e.firebaseapp.com',
    storageBucket: 'tradget-7498e.appspot.com',
    measurementId: 'G-B9Q20ZV5EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABd1ZjeXq5QcEhp3desha_ip3kN4AQiP4',
    appId: '1:866164282450:android:dbda3ba158f3885f8cfb8b',
    messagingSenderId: '866164282450',
    projectId: 'tradget-7498e',
    storageBucket: 'tradget-7498e.appspot.com',
  );
}
